#!/usr/bin/env perl

use warnings;
use strict;

use Cwd;
use Data::Dumper;
use File::Find;
use File::Path;
use IPC::System::Simple qw(run);
use List::MoreUtils qw(uniq);
use POSIX ();

use FindBin;
use lib "$FindBin::RealBin/lib";

use Slot;

sub usage;
sub become_cyrus;

my $SLOT_PATH = '/cyrus/slot';
my $SLOT_DEFAULTS = "$SLOT_PATH/defaults";

my %CMD_REFS = (
    'init' => \&cmd_init,
    'force-init' => \&cmd_init,

    'configure' => \&cmd_configure,
    'build' => \&cmd_build,
    'check' => \&cmd_check,
    'install' => \&cmd_install,
    
    'fullbuild' => \&cmd_fullbuild,

    'start' => \&cmd_start,
    'stop' => \&cmd_stop,
);

my @saved_argv = @ARGV;

# check for valid slots
my $slot_spec = shift @ARGV;
my @slots = ($slot_spec eq '-a'
    ? Slot::slots()
    : Slot::slots_from_string($slot_spec)
);
exit usage if not scalar @slots;

# check for valid commands
my @commands = @ARGV;
exit usage if not scalar @commands;

my @bad_commands = grep {
    not exists $CMD_REFS{$_};
} @commands;

if (@bad_commands) {
    print STDERR 'error: unrecognised command';
    print STDERR 's' if scalar @bad_commands > 1;
    print STDERR ': ', join(', ', @bad_commands);
    print STDERR "\n";

    exit usage;
}

# become cyrus user
become_cyrus($0, @saved_argv);

# check that slot path exists and is valid
die "not a directory: '$SLOT_PATH'\n" if not -d $SLOT_PATH;
die "directory not readable: '$SLOT_PATH'\n" if not -r $SLOT_PATH;
die "directory not writeable: '$SLOT_PATH'\n" if not -w $SLOT_PATH;
die "directory not executable: '$SLOT_PATH'\n" if not -x $SLOT_PATH;
die "directory not owned by cyrus: '$SLOT_PATH'\n" if not -o $SLOT_PATH;

# run commands
my $g_current_slot;

foreach my $slot (@slots) {
    $g_current_slot = $slot;
    foreach my $command (@commands) {
	my $force = $command =~ m/^force-/;

	eval {
	    $CMD_REFS{$command}->($command, $slot, $force);
	};

	if ($@) {
	    print STDERR "error: $command slot $slot: $@\n";
	}
    }
}

exit 0;

#############################################################

sub usage {
    my ($code) = @_;
    $code = $code || 1;

    print STDERR << "JHLBGK";
usage: $0 slots command [command ...]

JHLBGK

    return $code;
}

sub become_cyrus {
    my ($zero, @args) = @_;

    my $cyrus = 'cyrus';

    my (undef, undef, $pw_uid, $pw_gid) = getpwnam $cyrus
	or die "no user named '$cyrus'\n";

    my $uid = POSIX::getuid();

    return if ($uid == $pw_uid); # already cyrus user

    if ($uid == 0) {
        POSIX::setgid($pw_gid)
            or die "cannot setgid to group $pw_gid: $!";
        POSIX::setuid($pw_uid)
            or die "cannot setuid to group $pw_uid: $!";
    }
    else {
        my @cmd = ( 'sudo', '-u', $cyrus, $zero, @args );
        exec {'sudo'} @cmd;
	die "sudo -u $cyrus failed: $?";
    }
}

sub install_defaults_cb {
    # skip the entry for the SLOT_DEFAULTS directory itself
    return if $File::Find::name eq $SLOT_DEFAULTS;

    my $slot_dir = Slot::slot_dir($g_current_slot);

    if (-d $File::Find::name) {
	my $dir = substr $File::Find::name, 1 + length $SLOT_DEFAULTS;
	$dir = "$slot_dir/$dir";

	if (not -d $dir and not mkdir $dir, 0770) {
	    die "$dir: $!";
	}
    }
    else {
	my $file = substr $File::Find::name, 1 + length $SLOT_DEFAULTS;
	$file = "$slot_dir/$file";

	open my $in, '<', $File::Find::name or die "$File::Find::name: $!";
	open my $out, '>', $file or die "$file: $!";

	while (<$in>) {
	    s{$SLOT_DEFAULTS/}{$slot_dir/}g;
	    print $out $_;
	}

	close $out;
	close $in;
    }
}

sub newer_file {
    my @files = @_;

    my $newest_mtime = 0;
    my $newest_file;

    foreach my $file (@files) {
	next if not -e $file;

	my $mtime = (stat($file))[9];

	if ($mtime > $newest_mtime) {
	    $newest_mtime = $mtime;
	    $newest_file = $file;
	}
    }

    return $newest_file;
}

sub require_slot {
    my ($slot) = @_;

    # check that the slot exists
    if (not -d Slot::slot_dir($slot)) {
	die "slot not initialised\n";
    }
}

sub require_slot_config {
    my ($slot) = @_;

    # check that source dir is configured for the correct slot
    if (newer_file(".slot", "Makefile", "configure") ne ".slot") {
	# missing or stale .slot file
	die "not configured for this slot\n";
    }

    my $dot_slot = do {
	local $/ = undef;
	open my $f, '<', '.slot' or die ".slot: $!";
	<$f>;
    };
    chomp $dot_slot;

    if ($dot_slot ne $slot) {
	# wrong .slot file
	die "configured for wrong slot ($dot_slot)\n";
    }
}

############################################

sub cmd_init {
    my ($command, $slot, $force) = @_;

    my $slot_dir = Slot::slot_dir($slot);

    if (-d $slot_dir) {
	if (not $force) {
	    die "already initialised\n";
	}
    }
    elsif (not mkdir $slot_dir, 0770) {
	die "mkdir failed: $!";
    }

    if (-d "$SLOT_DEFAULTS") {
	find(\&install_defaults_cb, $SLOT_DEFAULTS);
    }
}

sub cmd_configure {
    my ($command, $slot, $force) = @_;

    # sanity check
    if (getcwd !~ m/cyrus-imapd$/
	or not -e 'configure.ac'
	or not -e 'Makefile.am'
    ) {
	die "current directory doesn't look like a cyrus source tree\n";
    }
    
    # if configure doesn't exist or is older than configure.ac, autoreconf
    if ("configure.ac" eq newer_file "configure", "configure.ac") {
	print STDERR "configure doesn't exist or is stale, rebuilding\n";
	run qw( autoreconf -i -s );
    }

    # run configure
    my $cflags = '-g -O0 -Wall -Wextra -Werror';
    my @configure_args = qw(
	--enable-silent-rules
	--enable-coverage
	--enable-http
	--enable-unit-tests
	--enable-replication
	--with-openssl=yes
	--enable-nntp
	--enable-murder
	--enable-idled
    );

    my $slot_dir = Slot::slot_dir($slot);

    run "./configure",
	"CFLAGS=$cflags",
	"--prefix=$slot_dir/usr/cyrus",
	"--sysconfdir=$slot_dir/etc",
	@configure_args;

    # update .slot file
    open my $f, '>', '.slot';
    print $f "$slot\n";
    close $f;
}

sub cmd_build {
    my ($command, $slot, $force) = @_;

    require_slot_config($slot);
    run qw( make lex-fix );
    run qw( make -j 16 );
}

sub cmd_check {
    my ($command, $slot, $force) = @_;

    require_slot_config($slot);
    run qw( make check );
}

sub cmd_install {
    my ($command, $slot, $force) = @_;

    require_slot($slot);
    require_slot_config($slot);
    run qw( make install );
}

sub cmd_fullbuild {
    my ($command, $slot, $force) = @_;

    # make configure.ac look newer than anything else
    utime(undef, undef, "configure.ac");

    cmd_configure($command, $slot, $force);
    cmd_build($command, $slot, $force);
    cmd_check($command, $slot, $force);
}

sub cmd_start {
    my ($command, $slot, $force) = @_;

    require_slot($slot);

    my $pidfile = Slot::slot_pidfile($slot);

    if (-e $pidfile) {
	my $pid = do {
	    local $/ = undef;
	    open my $fh, '<', $pidfile or die "$pidfile: $!";
	    <$fh>;
	};
	chomp $pid;

	die "pid file exists ($pid). already running?\n";
    }

    my $master = Slot::slot_binary($slot, 'master');

    print "sudo $master -d -p $pidfile\n";
}

sub cmd_stop {
    my ($command, $slot, $force) = @_;

    require_slot($slot);

    my $pidfile = Slot::slot_pidfile($slot);

    if (not -e $pidfile) {
	die "not running\n";
    }

    my $pid = do {
	local $/ = undef;
	open my $fh, '<', $pidfile or die "$pidfile: $!";
	<$fh>;
    };

    chomp $pid;

    die "invalid pid file: $pidfile\n" if not $pid or $pid < 0;

    print STDERR "trying nice shutdown...\n";

    kill 'QUIT', $pid;
    foreach my $sec (0..10) {
	if (kill 0, $pid) {
	    print STDERR "still alive after $sec seconds...\n";
	    sleep 1;
	}
	else {
	    last;
	}
    }
    if (kill 0, $pid) {
	print STDERR "killing hard...\n";
	kill 'TERM', $pid;
    }

    if (kill 0, $pid) {
	die "unable to kill $pid even with sigterm??";
    }

    print STDERR "done\n";

    unlink $pidfile or die "unlink $pidfile: $!";
}
